name: Canary Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:      # Allows manual trigger from GitHub UI

permissions:
  id-token: write
  contents: read

env:
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_TEST_USERNAME: ${{ secrets.COGNITO_TEST_USERNAME }}
  COGNITO_TEST_PASSWORD: ${{ secrets.COGNITO_TEST_PASSWORD }}
  COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ISSUER_URI: ${{ secrets.ISSUER_URI }}
  JWKS_URI: ${{ secrets.JWKS_URI }}
  IDP_GROUP_CLAIM_NAME: ${{ vars.IDP_GROUP_CLAIM_NAME }}

jobs:
  express-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        express-version: 
          - '4.x'
          - 'latest'
      fail-fast: false

    name: Test Express v${{ matrix.express-version }}

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build
    - name: Install sample app dependencies
      run: |
        cd examples/finish
        npm install
        npm install express@${{ matrix.express-version }}
        npm ls express
    - name: Start Express App
      run: cd examples/finish && npm start &
    - name: Wait for server
      run: sleep 10
    - name: Run Integration Tests
      run: npm run test:integration